name: Integration

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Run Composite Build Action
      uses: ./.github/actions/build 
    
    - name: Run Integration Tests
      run: cargo test --test '*' 
