name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Run Composite Build Action
      uses: ./.github/actions/build 
    
    - name: Run Unit Tests
      run: cargo test --bins --lib --verbose
